kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: node:16-alpine
    commands:
      - yarn
      - yarn test
      - yarn build
  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host: suprachat.net
      username: apiuser
      key:
        from_secret: ssh-key
      port: 39901
      command_timeout: 2m
      script:
        - sh build-admin.sh

